Algoritmo "AcademiaFuturo"

Var

   aluno : caractere
   peso,altura,imc : real

Inicio

      Escreval("Bem vindo(a) a Academia Futuro")
      Escreval("Digite o seu nome")
      Leia(aluno)
      Escreval("Bem vindo(a) ",aluno)
      Escreval("Qual a altura?")
      Leia(altura)
      Escreval("Qual o peso?")
      Leia(peso)
      imc <- peso/(altura*altura)
      Escreval("O seu imc é: ", imc:4:2)
      
      


      

Fimalgoritmo